import './globals.css';
import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import localFont from 'next/font/local';
import FloatingAssetsWrapper from '@/components/ui/FloatingAssetsWrapper';

const pixel = localFont({ src: '../../public/fonts/PixeloidSans.ttf' });

export const metadata: Metadata = {
  title: 'Converse',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={pixel.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
